# Generated by Django 3.2.8 on 2021-11-05 20:57

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('crm', models.IntegerField(verbose_name='Crm')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo_de_servico', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('arquivo', models.FileField(blank=True, upload_to=core.models.get_file_path, verbose_name='Arquivo')),
                ('mensagem', models.TextField(max_length=450, verbose_name='Mensagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='nome_modal',
            field=models.CharField(default='modal', max_length=100, verbose_name='Nome Modal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-home', 'Casa'), ('lni-car', 'Carro'), ('lni-bi-cycle', 'Moto'), ('lni-paperclip', 'Papel'), ('lni-agenda', 'Agenda'), ('lni-bolt-alt', 'Raio')], max_length=13, verbose_name='Icone'),
        ),
    ]
