# Generated by Django 3.2.8 on 2021-11-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='crm',
            field=models.CharField(max_length=13, verbose_name='Crm'),
        ),
    ]
