# Generated by Django 3.2.8 on 2021-11-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitacaoservico_id_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='id_observacao',
            field=models.FloatField(default=304400, verbose_name='Id Observação'),
        ),
    ]
