# Generated by Django 3.2.8 on 2021-10-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-home', 'Casa'), ('lni-car', 'Carro'), ('lni-bi-cycle', 'Moto'), ('lni-paperclip', 'Papel'), ('lni-agenda', 'Agenda'), ('lni-bolt-alt', 'Raio')], max_length=13, verbose_name='Icone'),
        ),
    ]
