# Generated by Django 3.2.8 on 2021-10-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='nome_modal',
            field=models.CharField(default='modal', max_length=100, verbose_name='Nome Modal'),
        ),
    ]
