# Generated by Django 3.2.8 on 2021-11-05 00:03

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servico_nome_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('crm', models.IntegerField(verbose_name='Crm')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo_de_servico', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('imagem', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
                ('mensagem', models.TextField(max_length=450, verbose_name='Mensagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
