# Generated by Django 3.2.8 on 2021-11-09 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_solicitacaoservico_id_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoservico',
            name='id_observacao',
        ),
    ]
