# Generated by Django 3.2.8 on 2021-11-09 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_solicitacaoservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='data_criado',
            field=models.CharField(default=datetime.date(2021, 11, 9), max_length=15, verbose_name='Data Criado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criado',
            field=models.CharField(default=datetime.date(2021, 11, 9), max_length=15, verbose_name='Data Criado'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_criado',
            field=models.CharField(default=datetime.date(2021, 11, 9), max_length=15, verbose_name='Data Criado'),
        ),
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='data_criado',
            field=models.CharField(default=datetime.date(2021, 11, 9), max_length=15, verbose_name='Data Criado'),
        ),
    ]
