# Generated by Django 3.2.8 on 2021-11-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211109_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='status',
            field=models.CharField(blank=True, choices=[('Em/U+0020/aberto', 'Em aberto'), ('Em andamento', 'Em andamento'), ('Concluida', 'Concluida')], default='Em aberto', max_length=100, verbose_name='Status'),
        ),
    ]
