# Generated by Django 3.2.8 on 2021-11-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_solicitacaoservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='status',
            field=models.CharField(blank=True, choices=[('Em\x08aberto', 'Em\x08aberto'), ('Em\x08andamento', 'Em\x08aberto'), ('Concluida', 'Concluida')], default='Em aberto', max_length=100, verbose_name='Status'),
        ),
    ]
