# Generated by Django 3.2.8 on 2021-11-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_solicitacaoservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='status',
            field=models.CharField(blank=True, choices=[('Em-aberto', 'Em-aberto'), ('Em-andamento', 'Em-aberto'), ('Concluida', 'Concluida')], default='Em aberto', max_length=100, verbose_name='Status'),
        ),
    ]
