# Generated by Django 3.2.8 on 2021-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_solicitacaoservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='status',
            field=models.CharField(blank=True, choices=[('Em_Aberto', 'Em_Aberto'), ('Em_Andamento', 'Em_Andamento'), ('Concluida', 'Concluida')], default='Em aberto', max_length=13, verbose_name='Status'),
        ),
    ]
