# Generated by Django 3.2.8 on 2021-11-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_solicitacaoservico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='solicitacaoservico',
            name='ativo',
        ),
        migrations.AddField(
            model_name='cargo',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado?'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado?'),
        ),
        migrations.AddField(
            model_name='servico',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado?'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado?'),
        ),
    ]
