# Generated by Django 3.2.8 on 2021-11-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211109_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='observacao',
            field=models.TextField(blank=True, max_length=250, verbose_name='Observação'),
        ),
    ]
