# Generated by Django 3.2.8 on 2021-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_solicitacaoservico_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='observacao',
            field=models.TextField(blank=True, max_length=450, verbose_name='Observação'),
        ),
    ]
