# Generated by Django 3.2.8 on 2021-11-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_solicitacaoservico_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='data_criado',
            field=models.CharField(default='13/11/2021', max_length=15, verbose_name='Data_Criado'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Membro da equipe?'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criado',
            field=models.CharField(default='13/11/2021', max_length=15, verbose_name='Data_Criado'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_criado',
            field=models.CharField(default='13/11/2021', max_length=15, verbose_name='Data_Criado'),
        ),
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='data_criado',
            field=models.CharField(default='13/11/2021', max_length=15, verbose_name='Data_Criado'),
        ),
    ]
