# Generated by Django 3.2.8 on 2022-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20211113_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='data_criado',
            field=models.CharField(default='15/06/2022', max_length=15, verbose_name='Data_Criado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criado',
            field=models.CharField(default='15/06/2022', max_length=15, verbose_name='Data_Criado'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_criado',
            field=models.CharField(default='15/06/2022', max_length=15, verbose_name='Data_Criado'),
        ),
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='data_criado',
            field=models.CharField(default='15/06/2022', max_length=15, verbose_name='Data_Criado'),
        ),
    ]
